assets:
  plugins:
    css: { autoprefixer: {}}
    img: { optim: {}}
  source_maps: false
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/yarn

exclude:
  - .travis.yml
  - bin/*
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md
  - yarn.lock

ga_analytics: # Add Google Analytics tracking code

plugins:
  - jekyll-assets
  - jekyll-sitemap

name: dxshen11_github_io

permalink: pretty

url: # Add your site url
