# General Settings
name: Dennis Shen
job_title: M.S. Mechanical Engineering - UCLA
email: dennisxinshen@ucla.edu
description: I am currently a M.S. candidate at UCLA studying mechanical engineering with a breadth in engineering design, as well as a smaller focus in mechanics and machine learning. My professional experiences include the medical device, product development, and aerospace industries.
avatar: /assets/images/face.jpg
# favicon: /favicon.ico
# twitter_handler: your_handler
# analytics_code: UA-XXXXXXX-2
# disqus: your_disqus_site

# Social Accounts
social_networks:
-  { name: facebook, url: '' }
-  { name: twitter, url: '' }
-  { name: instagram, url: '' }
-  { name: google-plus, url: '' }
-  { name: linkedin, url: 'https://www.linkedin.com/in/dennisxinshen/' }
-  { name: skype, url: '' }
-  { name: github, url: 'https://github.com/dxshen11' }
-  { name: codepen, url: '' }
-  { name: stack-overflow, url: '' }
-  { name: dribbble, url: '' }
-  { name: behance, url: '' }
-  { name: pinterest, url: '' }
-  { name: tumblr, url: '' }
-  { name: youtube, url: '' }
-  { name: vimeo, url: '' }
-  { name: vine, url: '' }
-  { name: 500px, url: '' }
-  { name: flickr, url: '' }
-  { name: spotify, url: '' }
-  { name: steam, url: '' }
-  { name: wordpress, url: '' }
-  { name: xing, url: '' }
-  { name: bitcoin, url: '' }
-  { name: pocket, url: '' }
-  { name: applemusic, url: '' }

# Modules Settings
show_categories: 1
show_tags: 1
show_email: 1
show_rss: 0
show_comments: 0
show_menu: 1
fixed_sidebar: 0

# Collections:
collections:
  education:
    output: true
    permalink: /education/:path/
  projects:
    output: true
    permalink: /projects/:path/
  experiences:
    output: true
    permalink: /experiences/:path/

  
# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: "true"

# Serving
url: ""
baseurl: ""

# Includes
include: ["_pages"]

# Outputting
permalink: /:categories/:title.html
category_dir: categories

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Conversion
markdown: kramdown
excerpt_separator: <!--more-->

# Assets Settings
sass:
  sass_dir: assets/partials
  style: compressed

